import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1784913423818 implements MigrationInterface {
    name = 'Migration1784913423818'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`user_codes\` (\`id\` int NOT NULL AUTO_INCREMENT, \`user_id\` int NOT NULL, \`code\` varchar(255) NULL, \`expired_at\` timestamp NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`transactions\` (\`id\` int NOT NULL AUTO_INCREMENT, \`wallet_id\` int NOT NULL, \`type\` varchar(255) NULL, \`amount\` decimal NULL, \`status\` varchar(255) NULL, \`description\` text NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`wallets\` (\`id\` int NOT NULL AUTO_INCREMENT, \`user_id\` int NOT NULL, \`balance\` decimal NOT NULL DEFAULT '0', \`pending_balance\` decimal NOT NULL DEFAULT '0', UNIQUE INDEX \`REL_92558c08091598f7a4439586cd\` (\`user_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`reward_appeals\` (\`id\` int NOT NULL AUTO_INCREMENT, \`reason\` text NULL, \`status\` varchar(255) NULL, \`proof_id\` int NULL, \`user_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`reward_proofs\` (\`id\` int NOT NULL AUTO_INCREMENT, \`video_url\` varchar(255) NULL, \`image_url\` varchar(255) NULL, \`description\` text NULL, \`ai_score\` decimal NULL, \`reward_coin\` decimal NULL, \`status\` varchar(255) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`user_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`product_variants\` (\`id\` int NOT NULL AUTO_INCREMENT, \`product_id\` int NOT NULL, \`deleted_at\` datetime(6) NULL, \`size\` varchar(255) NULL, \`color\` varchar(255) NULL, \`stock\` int NULL, \`weight\` float NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`comments\` (\`id\` int NOT NULL AUTO_INCREMENT, \`product_id\` int NOT NULL, \`user_id\` int NOT NULL, \`content\` text NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`likes\` (\`id\` int NOT NULL AUTO_INCREMENT, \`product_id\` int NOT NULL, \`user_id\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`reports\` (\`id\` int NOT NULL AUTO_INCREMENT, \`product_id\` int NOT NULL, \`user_id\` int NOT NULL, \`reason\` text NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`Provinces\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`Warehouses\` (\`id\` int NOT NULL AUTO_INCREMENT, \`warehouse_name\` varchar(255) NOT NULL, \`ward_id\` int NOT NULL, \`address_detail\` text NULL, \`lat\` decimal(10,8) NOT NULL, \`lng\` decimal(11,8) NOT NULL, \`pick_support\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`Wards\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`provinces_id\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`addresses\` (\`id\` int NOT NULL AUTO_INCREMENT, \`user_id\` int NOT NULL, \`ward_id\` int NOT NULL, \`address_name\` varchar(255) NULL, \`address_detail\` text NULL, \`lat\` decimal(10,8) NOT NULL, \`lng\` decimal(11,8) NOT NULL, \`is_default\` tinyint NOT NULL DEFAULT 0, \`deleted_at\` datetime(6) NULL, \`receiver_name\` varchar(255) NOT NULL, \`phone\` varchar(255) NOT NULL, \`full_address\` text NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`shipping\` (\`id\` int NOT NULL AUTO_INCREMENT, \`order_id\` int NOT NULL, \`address_id\` int NULL, \`shipper_id\` int NULL, \`status\` varchar(255) NULL, \`tracking_code\` varchar(255) NULL, UNIQUE INDEX \`REL_a37456893780ce2dfe0a7484c2\` (\`order_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`Status\` (\`id\` int NOT NULL AUTO_INCREMENT, \`status_name\` varchar(255) NULL, \`status_detail\` varchar(255) NULL, \`create_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`order_id\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`order_timelines\` (\`id\` int NOT NULL AUTO_INCREMENT, \`order_id\` int NOT NULL, \`status\` varchar(255) NOT NULL, \`note\` text NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`orders\` (\`id\` int NOT NULL AUTO_INCREMENT, \`buyer_id\` int NOT NULL, \`buyer_address_id\` int NULL, \`seller_id\` int NOT NULL, \`seller_address_id\` int NULL, \`status_id\` int NULL, \`status\` enum ('pending', 'confirmed', 'shipping', 'delivered', 'cancelled', 'refunded') NOT NULL DEFAULT 'pending', \`total_price\` decimal NULL DEFAULT '0', \`shipping_fee\` decimal NULL DEFAULT '0', \`leatime\` int NULL DEFAULT '0', \`note\` text NULL, \`cancel_reason\` varchar(255) NULL, \`refund_reason\` varchar(255) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`order_items\` (\`id\` int NOT NULL AUTO_INCREMENT, \`order_id\` int NOT NULL, \`product_id\` int NOT NULL, \`total_price\` decimal NULL, \`quantity\` int NULL, \`variant_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`categories\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`parent_id\` int NULL DEFAULT '0', \`sort\` int NULL DEFAULT '0', \`has_child\` tinyint NULL DEFAULT 0, \`has_brand\` tinyint NULL DEFAULT 0, \`has_size\` tinyint NULL DEFAULT 0, \`require_weight\` tinyint NULL DEFAULT 0, \`description\` varchar(255) NULL, \`image_url\` varchar(255) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`brands\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`logo_url\` varchar(255) NULL, \`category_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`cart_items\` (\`id\` int NOT NULL AUTO_INCREMENT, \`user_id\` int NOT NULL, \`product_id\` int NOT NULL, \`quantity\` int NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_b2c6ebe6bd6f9a4e6bbd8ab082\` (\`user_id\`, \`product_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`products\` (\`id\` int NOT NULL AUTO_INCREMENT, \`seller_id\` int NOT NULL, \`ship_from_id\` int NOT NULL, \`category_id\` int NULL, \`brand_id\` int NULL, \`title\` varchar(255) NULL, \`description\` text NULL, \`price\` decimal NULL, \`price_discount\` decimal NULL, \`videos\` json NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`image_urls\` text NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`conversations\` (\`id\` int NOT NULL AUTO_INCREMENT, \`time_last_update\` int NULL, \`time_last_seen\` int NULL, \`last_messasge_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`messages\` (\`id\` int NOT NULL AUTO_INCREMENT, \`content\` varchar(255) NOT NULL, \`type\` varchar(255) NOT NULL, \`created_at\` int NULL, \`conversation_id\` int NULL, \`sender_id\` int NULL, \`receiver_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_follows\` (\`id\` int NOT NULL AUTO_INCREMENT, \`follower_id\` int NOT NULL, \`followee_id\` int NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_user_follows_followee_id\` (\`followee_id\`), INDEX \`IDX_user_follows_follower_id\` (\`follower_id\`), UNIQUE INDEX \`UQ_user_follows_follower_followee\` (\`follower_id\`, \`followee_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`notifications\` (\`id\` int NOT NULL AUTO_INCREMENT, \`type\` varchar(255) NOT NULL, \`product_id\` int NULL, \`object_id\` int NOT NULL, \`title\` varchar(255) NOT NULL, \`created_at\` int NOT NULL, \`avatar\` varchar(255) NULL, \`group\` int NULL, \`read\` tinyint NOT NULL, \`user_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` int NOT NULL AUTO_INCREMENT, \`username\` varchar(255) NULL, \`email\` varchar(255) NULL, \`phonenumber\` varchar(255) NULL, \`password\` varchar(255) NOT NULL, \`uuid\` varchar(255) NULL, \`role\` varchar(255) NULL, \`fullName\` varchar(255) NULL, \`firstName\` varchar(255) NULL, \`lastName\` varchar(255) NULL, \`address\` varchar(255) NULL, \`city\` varchar(255) NULL, \`status\` varchar(255) NULL, \`cover_image\` varchar(255) NULL, \`cover_image_web\` varchar(255) NULL, \`avatar\` varchar(255) NULL, \`bio\` text NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`reward_rules\` (\`id\` int NOT NULL AUTO_INCREMENT, \`battle_type\` varchar(255) NULL, \`reward_coin\` decimal NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`news\` (\`id\` int NOT NULL AUTO_INCREMENT, \`title\` text NULL, \`created_at\` int NULL, \`content\` varchar(255) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`dev_tokens\` (\`id\` int NOT NULL AUTO_INCREMENT, \`user_id\` int NOT NULL, \`devtype\` varchar(10) NOT NULL, \`devtoken\` varchar(512) NOT NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_115a64b0db661b17e4625640a9\` (\`user_id\`), UNIQUE INDEX \`IDX_88b54cb5233e3bb8cf83827df1\` (\`devtoken\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_blocks\` (\`id\` int NOT NULL AUTO_INCREMENT, \`blocker_id\` int NOT NULL, \`blocked_id\` int NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_user_blocks_blocked_id\` (\`blocked_id\`), INDEX \`IDX_user_blocks_blocker_id\` (\`blocker_id\`), UNIQUE INDEX \`UQ_user_blocks_blocker_blocked\` (\`blocker_id\`, \`blocked_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`push_settings\` (\`id\` int NOT NULL AUTO_INCREMENT, \`user_id\` int NOT NULL, \`like\` tinyint NOT NULL DEFAULT '1', \`comment\` tinyint NOT NULL DEFAULT '1', \`transaction\` tinyint NOT NULL DEFAULT '1', \`announcement\` tinyint NOT NULL DEFAULT '1', \`sound_on\` tinyint NOT NULL DEFAULT '1', \`sound_default\` varchar(50) NOT NULL DEFAULT 'default', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_00b9281ead6050207252a2e0f9\` (\`user_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`rates\` (\`id\` int NOT NULL AUTO_INCREMENT, \`user_id\` int NOT NULL, \`reviewer_id\` int NULL, \`product_id\` int NULL, \`purchase_id\` int NULL, \`level\` int NOT NULL, \`content\` text NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`saved_searches\` (\`id\` int NOT NULL AUTO_INCREMENT, \`user_id\` int NOT NULL, \`keyword\` varchar(255) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`conversations_users_users\` (\`conversationsId\` int NOT NULL, \`usersId\` int NOT NULL, INDEX \`IDX_35bd28a66d1a6e3eefa386815e\` (\`conversationsId\`), INDEX \`IDX_bc56bf8e5f76472688210e9a99\` (\`usersId\`), PRIMARY KEY (\`conversationsId\`, \`usersId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`user_codes\` ADD CONSTRAINT \`FK_b98f6d82aa9b218599917bf21b3\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transactions\` ADD CONSTRAINT \`FK_0b171330be0cb621f8d73b87a9e\` FOREIGN KEY (\`wallet_id\`) REFERENCES \`wallets\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`wallets\` ADD CONSTRAINT \`FK_92558c08091598f7a4439586cda\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reward_appeals\` ADD CONSTRAINT \`FK_d69e89386d02bbb92928f22e91b\` FOREIGN KEY (\`proof_id\`) REFERENCES \`reward_proofs\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reward_appeals\` ADD CONSTRAINT \`FK_b7c1f74ef73b47659aec8552754\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reward_proofs\` ADD CONSTRAINT \`FK_0892e58edefdf3aa9656fd1bbb9\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_variants\` ADD CONSTRAINT \`FK_6343513e20e2deab45edfce1316\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comments\` ADD CONSTRAINT \`FK_8f405e50bbc3adb9a80fac0f928\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comments\` ADD CONSTRAINT \`FK_4c675567d2a58f0b07cef09c13d\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`likes\` ADD CONSTRAINT \`FK_35eb9e9cc6f706f1a9af2f9d158\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`likes\` ADD CONSTRAINT \`FK_3f519ed95f775c781a254089171\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reports\` ADD CONSTRAINT \`FK_0ba6a2ea28e6e64af44e4e1cc6d\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reports\` ADD CONSTRAINT \`FK_ca7a21eb95ca4625bd5eaef7e0c\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Warehouses\` ADD CONSTRAINT \`FK_05479f6fa62443bfd5b67c26c4e\` FOREIGN KEY (\`ward_id\`) REFERENCES \`Wards\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Wards\` ADD CONSTRAINT \`FK_47267a6978e1d13f2e9375df8e4\` FOREIGN KEY (\`provinces_id\`) REFERENCES \`Provinces\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`addresses\` ADD CONSTRAINT \`FK_16aac8a9f6f9c1dd6bcb75ec023\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`addresses\` ADD CONSTRAINT \`FK_e3357fb2a564d718901b950ed41\` FOREIGN KEY (\`ward_id\`) REFERENCES \`Wards\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`shipping\` ADD CONSTRAINT \`FK_a37456893780ce2dfe0a7484c22\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`shipping\` ADD CONSTRAINT \`FK_facb0fff23b713c9e09b2da88f6\` FOREIGN KEY (\`address_id\`) REFERENCES \`addresses\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Status\` ADD CONSTRAINT \`FK_c1b19eacf6435ffbbacb5b3724b\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_timelines\` ADD CONSTRAINT \`FK_1e1ba82c0e8bf43bef6d080ecfa\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_5e90e93d0e036c3fadbaefa4d0a\` FOREIGN KEY (\`buyer_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_ef6710c78c6fbc26d1ba58268ab\` FOREIGN KEY (\`seller_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_fd91a8eb24848c6e3af43f2f734\` FOREIGN KEY (\`buyer_address_id\`) REFERENCES \`addresses\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_459f1e0cca2c4234340a7d57ce4\` FOREIGN KEY (\`seller_address_id\`) REFERENCES \`addresses\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_145532db85752b29c57d2b7b1f1\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_9263386c35b6b242540f9493b00\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_db2d0ea722e16e0fe8ab3bce111\` FOREIGN KEY (\`variant_id\`) REFERENCES \`product_variants\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` ADD CONSTRAINT \`FK_b7213c20c1ecdc6597abc8f1212\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` ADD CONSTRAINT \`FK_30e89257a105eab7648a35c7fce\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_425ee27c69d6b8adc5d6475dcfe\` FOREIGN KEY (\`seller_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_4918144a05b35d8d6c4f92c293e\` FOREIGN KEY (\`ship_from_id\`) REFERENCES \`addresses\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_9a5f6868c96e0069e699f33e124\` FOREIGN KEY (\`category_id\`) REFERENCES \`categories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_1530a6f15d3c79d1b70be98f2be\` FOREIGN KEY (\`brand_id\`) REFERENCES \`brands\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD CONSTRAINT \`FK_3bc55a7c3f9ed54b520bb5cfe23\` FOREIGN KEY (\`conversation_id\`) REFERENCES \`conversations\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD CONSTRAINT \`FK_22133395bd13b970ccd0c34ab22\` FOREIGN KEY (\`sender_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD CONSTRAINT \`FK_b561864743d235f44e70addc1f5\` FOREIGN KEY (\`receiver_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_follows\` ADD CONSTRAINT \`FK_f7af3bf8f2dcba61b4adc108239\` FOREIGN KEY (\`follower_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_follows\` ADD CONSTRAINT \`FK_ad9563c49281be94000f50a4308\` FOREIGN KEY (\`followee_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD CONSTRAINT \`FK_9a8a82462cab47c73d25f49261f\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`dev_tokens\` ADD CONSTRAINT \`FK_115a64b0db661b17e4625640a96\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_blocks\` ADD CONSTRAINT \`FK_dfcd8a81016d1de587fbd2d70bf\` FOREIGN KEY (\`blocker_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_blocks\` ADD CONSTRAINT \`FK_7a0806a54f0ad9ced3e247cacd1\` FOREIGN KEY (\`blocked_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`push_settings\` ADD CONSTRAINT \`FK_00b9281ead6050207252a2e0f92\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`conversations_users_users\` ADD CONSTRAINT \`FK_35bd28a66d1a6e3eefa386815e8\` FOREIGN KEY (\`conversationsId\`) REFERENCES \`conversations\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`conversations_users_users\` ADD CONSTRAINT \`FK_bc56bf8e5f76472688210e9a996\` FOREIGN KEY (\`usersId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`conversations_users_users\` DROP FOREIGN KEY \`FK_bc56bf8e5f76472688210e9a996\``);
        await queryRunner.query(`ALTER TABLE \`conversations_users_users\` DROP FOREIGN KEY \`FK_35bd28a66d1a6e3eefa386815e8\``);
        await queryRunner.query(`ALTER TABLE \`push_settings\` DROP FOREIGN KEY \`FK_00b9281ead6050207252a2e0f92\``);
        await queryRunner.query(`ALTER TABLE \`user_blocks\` DROP FOREIGN KEY \`FK_7a0806a54f0ad9ced3e247cacd1\``);
        await queryRunner.query(`ALTER TABLE \`user_blocks\` DROP FOREIGN KEY \`FK_dfcd8a81016d1de587fbd2d70bf\``);
        await queryRunner.query(`ALTER TABLE \`dev_tokens\` DROP FOREIGN KEY \`FK_115a64b0db661b17e4625640a96\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP FOREIGN KEY \`FK_9a8a82462cab47c73d25f49261f\``);
        await queryRunner.query(`ALTER TABLE \`user_follows\` DROP FOREIGN KEY \`FK_ad9563c49281be94000f50a4308\``);
        await queryRunner.query(`ALTER TABLE \`user_follows\` DROP FOREIGN KEY \`FK_f7af3bf8f2dcba61b4adc108239\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP FOREIGN KEY \`FK_b561864743d235f44e70addc1f5\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP FOREIGN KEY \`FK_22133395bd13b970ccd0c34ab22\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP FOREIGN KEY \`FK_3bc55a7c3f9ed54b520bb5cfe23\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_1530a6f15d3c79d1b70be98f2be\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_9a5f6868c96e0069e699f33e124\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_4918144a05b35d8d6c4f92c293e\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_425ee27c69d6b8adc5d6475dcfe\``);
        await queryRunner.query(`ALTER TABLE \`cart_items\` DROP FOREIGN KEY \`FK_30e89257a105eab7648a35c7fce\``);
        await queryRunner.query(`ALTER TABLE \`cart_items\` DROP FOREIGN KEY \`FK_b7213c20c1ecdc6597abc8f1212\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_db2d0ea722e16e0fe8ab3bce111\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_9263386c35b6b242540f9493b00\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_145532db85752b29c57d2b7b1f1\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_459f1e0cca2c4234340a7d57ce4\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_fd91a8eb24848c6e3af43f2f734\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_ef6710c78c6fbc26d1ba58268ab\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_5e90e93d0e036c3fadbaefa4d0a\``);
        await queryRunner.query(`ALTER TABLE \`order_timelines\` DROP FOREIGN KEY \`FK_1e1ba82c0e8bf43bef6d080ecfa\``);
        await queryRunner.query(`ALTER TABLE \`Status\` DROP FOREIGN KEY \`FK_c1b19eacf6435ffbbacb5b3724b\``);
        await queryRunner.query(`ALTER TABLE \`shipping\` DROP FOREIGN KEY \`FK_facb0fff23b713c9e09b2da88f6\``);
        await queryRunner.query(`ALTER TABLE \`shipping\` DROP FOREIGN KEY \`FK_a37456893780ce2dfe0a7484c22\``);
        await queryRunner.query(`ALTER TABLE \`addresses\` DROP FOREIGN KEY \`FK_e3357fb2a564d718901b950ed41\``);
        await queryRunner.query(`ALTER TABLE \`addresses\` DROP FOREIGN KEY \`FK_16aac8a9f6f9c1dd6bcb75ec023\``);
        await queryRunner.query(`ALTER TABLE \`Wards\` DROP FOREIGN KEY \`FK_47267a6978e1d13f2e9375df8e4\``);
        await queryRunner.query(`ALTER TABLE \`Warehouses\` DROP FOREIGN KEY \`FK_05479f6fa62443bfd5b67c26c4e\``);
        await queryRunner.query(`ALTER TABLE \`reports\` DROP FOREIGN KEY \`FK_ca7a21eb95ca4625bd5eaef7e0c\``);
        await queryRunner.query(`ALTER TABLE \`reports\` DROP FOREIGN KEY \`FK_0ba6a2ea28e6e64af44e4e1cc6d\``);
        await queryRunner.query(`ALTER TABLE \`likes\` DROP FOREIGN KEY \`FK_3f519ed95f775c781a254089171\``);
        await queryRunner.query(`ALTER TABLE \`likes\` DROP FOREIGN KEY \`FK_35eb9e9cc6f706f1a9af2f9d158\``);
        await queryRunner.query(`ALTER TABLE \`comments\` DROP FOREIGN KEY \`FK_4c675567d2a58f0b07cef09c13d\``);
        await queryRunner.query(`ALTER TABLE \`comments\` DROP FOREIGN KEY \`FK_8f405e50bbc3adb9a80fac0f928\``);
        await queryRunner.query(`ALTER TABLE \`product_variants\` DROP FOREIGN KEY \`FK_6343513e20e2deab45edfce1316\``);
        await queryRunner.query(`ALTER TABLE \`reward_proofs\` DROP FOREIGN KEY \`FK_0892e58edefdf3aa9656fd1bbb9\``);
        await queryRunner.query(`ALTER TABLE \`reward_appeals\` DROP FOREIGN KEY \`FK_b7c1f74ef73b47659aec8552754\``);
        await queryRunner.query(`ALTER TABLE \`reward_appeals\` DROP FOREIGN KEY \`FK_d69e89386d02bbb92928f22e91b\``);
        await queryRunner.query(`ALTER TABLE \`wallets\` DROP FOREIGN KEY \`FK_92558c08091598f7a4439586cda\``);
        await queryRunner.query(`ALTER TABLE \`transactions\` DROP FOREIGN KEY \`FK_0b171330be0cb621f8d73b87a9e\``);
        await queryRunner.query(`ALTER TABLE \`user_codes\` DROP FOREIGN KEY \`FK_b98f6d82aa9b218599917bf21b3\``);
        await queryRunner.query(`DROP INDEX \`IDX_bc56bf8e5f76472688210e9a99\` ON \`conversations_users_users\``);
        await queryRunner.query(`DROP INDEX \`IDX_35bd28a66d1a6e3eefa386815e\` ON \`conversations_users_users\``);
        await queryRunner.query(`DROP TABLE \`conversations_users_users\``);
        await queryRunner.query(`DROP TABLE \`saved_searches\``);
        await queryRunner.query(`DROP TABLE \`rates\``);
        await queryRunner.query(`DROP INDEX \`IDX_00b9281ead6050207252a2e0f9\` ON \`push_settings\``);
        await queryRunner.query(`DROP TABLE \`push_settings\``);
        await queryRunner.query(`DROP INDEX \`UQ_user_blocks_blocker_blocked\` ON \`user_blocks\``);
        await queryRunner.query(`DROP INDEX \`IDX_user_blocks_blocker_id\` ON \`user_blocks\``);
        await queryRunner.query(`DROP INDEX \`IDX_user_blocks_blocked_id\` ON \`user_blocks\``);
        await queryRunner.query(`DROP TABLE \`user_blocks\``);
        await queryRunner.query(`DROP INDEX \`IDX_88b54cb5233e3bb8cf83827df1\` ON \`dev_tokens\``);
        await queryRunner.query(`DROP INDEX \`IDX_115a64b0db661b17e4625640a9\` ON \`dev_tokens\``);
        await queryRunner.query(`DROP TABLE \`dev_tokens\``);
        await queryRunner.query(`DROP TABLE \`news\``);
        await queryRunner.query(`DROP TABLE \`reward_rules\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP TABLE \`notifications\``);
        await queryRunner.query(`DROP INDEX \`UQ_user_follows_follower_followee\` ON \`user_follows\``);
        await queryRunner.query(`DROP INDEX \`IDX_user_follows_follower_id\` ON \`user_follows\``);
        await queryRunner.query(`DROP INDEX \`IDX_user_follows_followee_id\` ON \`user_follows\``);
        await queryRunner.query(`DROP TABLE \`user_follows\``);
        await queryRunner.query(`DROP TABLE \`messages\``);
        await queryRunner.query(`DROP TABLE \`conversations\``);
        await queryRunner.query(`DROP TABLE \`products\``);
        await queryRunner.query(`DROP INDEX \`IDX_b2c6ebe6bd6f9a4e6bbd8ab082\` ON \`cart_items\``);
        await queryRunner.query(`DROP TABLE \`cart_items\``);
        await queryRunner.query(`DROP TABLE \`brands\``);
        await queryRunner.query(`DROP TABLE \`categories\``);
        await queryRunner.query(`DROP TABLE \`order_items\``);
        await queryRunner.query(`DROP TABLE \`orders\``);
        await queryRunner.query(`DROP TABLE \`order_timelines\``);
        await queryRunner.query(`DROP TABLE \`Status\``);
        await queryRunner.query(`DROP INDEX \`REL_a37456893780ce2dfe0a7484c2\` ON \`shipping\``);
        await queryRunner.query(`DROP TABLE \`shipping\``);
        await queryRunner.query(`DROP TABLE \`addresses\``);
        await queryRunner.query(`DROP TABLE \`Wards\``);
        await queryRunner.query(`DROP TABLE \`Warehouses\``);
        await queryRunner.query(`DROP TABLE \`Provinces\``);
        await queryRunner.query(`DROP TABLE \`reports\``);
        await queryRunner.query(`DROP TABLE \`likes\``);
        await queryRunner.query(`DROP TABLE \`comments\``);
        await queryRunner.query(`DROP TABLE \`product_variants\``);
        await queryRunner.query(`DROP TABLE \`reward_proofs\``);
        await queryRunner.query(`DROP TABLE \`reward_appeals\``);
        await queryRunner.query(`DROP INDEX \`REL_92558c08091598f7a4439586cd\` ON \`wallets\``);
        await queryRunner.query(`DROP TABLE \`wallets\``);
        await queryRunner.query(`DROP TABLE \`transactions\``);
        await queryRunner.query(`DROP TABLE \`user_codes\``);
    }

}
